version: '3.5'
services:
  db:
    image: postgres:11
    container_name: johnshub_db
    restart: always
    environment:
      POSTGRES_DB: johnshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres
    networks:
      services-network:
        aliases:
          - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johnshub_api
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=johnshub
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    links:
      - db:db
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    volumes:
      - '.:/usr/src/johnshub'
    networks:
      services-network:
        aliases:
          - api

volumes:
  db_data:

networks:
  services-network:
    name: services-network
    driver: bridge