version: '3.5'
services:
  db:
    image: postgres
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      POSTGRES_DB: johnshub
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johnshub_backend
    hostname: johnshub_backend
    tty: true
    working_dir: /api
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
