version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: johnshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johnshub_backend
    hostname: johnshub_backend
    tty: true
    working_dir: /api
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=johnshub
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  db_data: