version: '3.5'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_HOST=%
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=komikaru
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - "./db:/var/lib/mysql"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: komikaru_backend
    hostname: komikaru_backend
    tty: true
    working_dir: /api
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
